### PR TITLE
Feature/25 default content update

### PR DESCRIPTION
**Pull request by finnlewis**
@msayoung just creating this to see how it is looking. 

I fixed the entity reference fixer in https://github.com/localgovdrupal/localgov_demo/commit/cf083576275287c2e95ddae32bb2b444921e358c

### CODE REVIEW

**Comment by finnlewis** [comment]
Tagging a few people in this in case anyone has time to test it locally. 

It is working for me!

**Comment by finnlewis** [comment]
@andybroomfield are you Ok to approve this insofar as the tests pass and it add lots of new content!
we noted there are (and will continue to be) improvements, but fot the sake of the sprint ... it would be good to merge.

**Comment by andybroomfield** [comment]
Seeing the following errors doing a fresh install and then enabling localgov_demo

````
[error]  Drupal\search_api\SearchApiException while adding Views handlers for field Content » Directory channels on index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 441 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
 [error]  Drupal\search_api\SearchApiException while computing Views data for index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 441 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
 [error]  Drupal\search_api\SearchApiException while adding Views handlers for field Content » Directory channels on index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 441 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
 [error]  Drupal\search_api\SearchApiException while computing Views data for index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 441 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
 [error]  Drupal\search_api\SearchApiException while adding Views handlers for field Content » Directory channels on index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 441 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
 [error]  Drupal\search_api\SearchApiException while computing Views data for index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 441 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
 [error]  Drupal\search_api\SearchApiException while adding Views handlers for field Content » Directory channels on index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 441 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
 [error]  Drupal\search_api\SearchApiException while computing Views data for index Directories: Could not retrieve data definition for field 'Directory channels' on index 'Directories'. in Drupal\search_api\Item\Field->getDataDefinition() (line 441 of /app/web/modules/contrib/search_api/src/Item/Field.php). 
````
Is that expected?

Otherwise content all seems to be there.
The only change I would do is remove one of the death banners, maybe replace it with an emergency. That can be a new PR though.

If the error is expected I can approve this, but it would be good to get those errors resolved soon as it would be concerning for a council looking to install it for the first time.

**Comment by stephen-cox** [comment]
> Seeing the following errors doing a fresh install and then enabling localgov_demo

I see that too. Looks to me like a bug in the directories module, although I don't see an issue for this. Will need to do some digging to determine what's causing it

**Comment by andybroomfield** [comment]
Thanks @stephen-cox.
As thats an issue with localgov_demo, there is no reason to hold up this release.

**Review by andybroomfield — APPROVED** [review]
Tested with fresh install and enabling localgov_demo

**Pull request merged**
