### PR TITLE
Drupal 10 support

### PR DESCRIPTION
**Pull request by stephen-cox**
This will require a 3.x release

### CODE REVIEW

**Comment by finnlewis** [comment]
Just installed Drupal 10 3.x branch of localgov_project with 
```
composer create-project localgovdrupal/localgov-project --stability dev MY_PROJECT 
```
Enabling localgov_demo works just fine! :smile:

**Comment by finnlewis** [comment]
Fixing coding standards.

**Review by finnlewis — APPROVED** [review]
Works for me locally, nice one @stephen-cox  and @ekes !

**Comment by ekes** [comment]
:+1: confirmed, let's get it merged and checking for bugs can continue.

**Pull request merged**
