### PR TITLE
Add a newsroom and update the news article references

### LINKED ISSUE #95: Add Newsroom to demo content, as no longer enabled on install

### PR DESCRIPTION
**Pull request by msayoung**

### CODE REVIEW

**Comment by andybroomfield** [comment]
I'm currently seeing
> Unable to install modules: module 'localgov_demo' is missing its dependency module media_library_edit.  
                              
Has the branch that install media_library_edit been released, and does it get installed?
Currently checking if its install order.

**Review by finnlewis — APPROVED** [review]
It works for me, thank you @msayoung

**Review by andybroomfield — APPROVED** [review]
This is working for me, though it was a manual install of the other modules before demo.

I think this is fine, as it's not demo that requires media_library_edit. It will be something else.

**Pull request merged**
