### PR TITLE
Feature/24 content tests

### LINKED ISSUE #24: Write tests for content from localgov_demo module ahead of upgrade testing
From localgovdrupal/localgov#181 

Write tests for the localgov_demo module (Estimate: 13)

Write browser tests to test that the expected content is present and displayed.
Starting this in the D8 branch as tests should be D8/D9 independent.
One test for each type of content = ~ 10 (+ events + news).

- [x] Write test for **service landing page** content in localgov_demo module
- [x] Write test for **service sub-landing page** page content in localgov_demo module 
- [x] Write test for **service page** content in localgov_demo module 
- [x] Write test for **step-by-step overview page** content in localgov_demo module 
- [x] Write test for **step-by-step page** content in localgov_demo module 
- [x] Write test for **guide overview page** content in localgov_demo module 
- [x] Write test for **guide page** content in localgov_demo module 
- [x] Write test for **event page** content in localgov_demo module

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by finnlewis** [comment]
Any ideas @stephen-cox ?

```
.......................................E...................... 65 / 82 ( 79%)
.................

Time: 12.56 minutes, Memory: 10.00 MB

There was 1 error:

1) Drupal\Tests\localgov_demo\Functional\ContentTest::testPageContent
Drupal\Core\Entity\EntityStorageException: An exception occurred while executing 'ATTACH DATABASE :db AS :prefix' with params ["\/dev\/shm\/test.sqlite-test54244979", "test54244979"]:

SQLSTATE[HY000]: General error: 5 database is locked

/var/www/html/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:846
/var/www/html/web/core/lib/Drupal/Core/Entity/EntityBase.php:395
/var/www/html/web/modules/contrib/default_content/src/Importer.php:246
/var/www/html/web/modules/contrib/default_content/default_content.module:15
/var/www/html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php:403
/var/www/html/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:347
/var/www/html/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
/var/www/html/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:476
/var/www/html/web/core/tests/Drupal/Tests/BrowserTestBase.php:578
/var/www/html/web/core/tests/Drupal/Tests/BrowserTestBase.php:406

FAILURES!
Tests: 82, Assertions: 1225, Failures: 0, Errors: 1.
Error: Process completed with exit code 2.
```

**Comment by finnlewis** [comment]
I couldn't replicate locally, even switching to sqlite.

**Comment by stephen-cox** [comment]
I have replicated it, but I'm not making any progress. It's an SQLite issue, but not getting anywhere with a solution

**Comment by finnlewis** [comment]
Interesting that you replicated it. 

I tried copying phpunit.dist.xml to phpunit.xml

Changing this line 

`    <env name="SIMPLETEST_DB" value="sqlite://localhost//dev/shm/test.sqlite."/>"/>`

Then running: 

` lando phpunit web/modules/contrib/localgov_demo/`

Did you do the same or something different?

**Comment by stephen-cox** [comment]
Might need to override the environmental variables set for the app container in your `.lando.dist.yml` file

**Comment by stephen-cox** [comment]
The issue seems to be in the importing of default content in SQLite. Nothing obvious in the default content or core issues queues. 

Tried patches on this issue but didn't help: https://www.drupal.org/project/drupal/issues/1120020

**Comment by stephen-cox** [comment]
Looks like there are multiple problems here.

The problem identified above is due to the alert banner module clearing caches when adding a new banner. Commenting this line out fixes this error when running test in SQLite: https://github.com/localgovdrupal/localgov_alert_banner/blob/ee7fafe8c896ba2af7524193163653dd7522177f/src/Entity/AlertBannerEntity.php#L149

Next problem that occurs is:

```
Drupal\Core\Entity\EntityStorageException: Table name must match the regex /^[a-zA-Z]\w{1,64}$/

/app/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:810
/app/web/core/lib/Drupal/Core/Entity/EntityBase.php:339
/app/web/modules/contrib/default_content/src/Importer.php:246
/app/web/modules/contrib/default_content/default_content.module:15
/app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php:403
/app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:352
/app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
/app/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:463
/app/web/core/tests/Drupal/Tests/BrowserTestBase.php:584
/app/web/core/tests/Drupal/Tests/BrowserTestBase.php:403
/app/vendor/phpunit/phpunit/src/Framework/TestResult.php:722

Caused by
InvalidArgumentException: Table name must match the regex /^[a-zA-Z]\w{1,64}$/

/app/vendor/previousnext/nested-set/src/Storage/BaseDbalStorage.php:42
/app/web/modules/contrib/entity_hierarchy/src/Storage/NestedSetStorage.php:74
/app/web/modules/contrib/entity_hierarchy/src/Storage/NestedSetStorageFactory.php:87
/app/web/modules/contrib/entity_hierarchy/src/Storage/NestedSetStorageFactory.php:71
/app/web/modules/contrib/entity_hierarchy/src/Plugin/Field/FieldType/EntityReferenceHierarchy.php:201
/app/web/modules/contrib/entity_hierarchy/src/Plugin/Field/FieldType/EntityReferenceHierarchy.php:128
/app/web/core/lib/Drupal/Core/Field/FieldItemList.php:233
/app/web/core/lib/Drupal/Core/Field/FieldItemList.php:198
/app/web/modules/contrib/entity_hierarchy/src/Plugin/Field/FieldType/EntityReferenceHierarchyFieldItemList.php:33
/app/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:838
/app/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:870
/app/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:792
/app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:530
/app/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:685
/app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:455
/app/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:801
/app/web/core/lib/Drupal/Core/Entity/EntityBase.php:339
/app/web/modules/contrib/default_content/src/Importer.php:246
/app/web/modules/contrib/default_content/default_content.module:15
/app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php:403
/app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:352
/app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
/app/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:463
/app/web/core/tests/Drupal/Tests/BrowserTestBase.php:584
/app/web/core/tests/Drupal/Tests/BrowserTestBase.php:403
/app/vendor/phpunit/phpunit/src/Framework/TestResult.php:722
```

This is thrown by the previousnext/nested-set module, that is pulled in by the Drupal Entity Hierarchy module, that is required by LocalGov Subsites module.

**Comment by finnlewis** [comment]
I'll try running the tests locally again.

**Comment by finnlewis** [comment]
Tests all pass locally: 

```
$ lando phpunit web/modules/contrib/localgov_demo/
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Testing /app/web/modules/contrib/localgov_demo
Content (Drupal\Tests\localgov_demo\Functional\Content)
 ✔ Page content

Time: 02:18.326, Memory: 14.00 MB

OK (1 test, 86 assertions)

**Comment by stephen-cox** [comment]
To see the issues you'll need to be running the tests in SQLite. They work fine for me locally when using MySQL but not SQLite.

**Comment by msayoung** [comment]
Blocked due to https://github.com/localgovdrupal/localgov/issues/253

**Comment by finnlewis** [comment]
No longer blocked @msayoung ! 

Just triggered the tests again, but we might need to update the actual tests as we've updated the actual content!

**Comment by finnlewis** [comment]
@msayoung @finnlewis - perhaps we can get this one moving again since we changed the test runners to use MySQL rather than SQLite

**Comment by finnlewis** [comment]
@finnlewis perhaps try creating a new Pull Request for this?

**Comment by finnlewis** [comment]
Closing to recreated.

**Pull request closed without merging**
